In [2]:
import tensorflow as tf
import numpy as np

In [4]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape, "\n ")
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3) 
 
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [5]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y: y_data}) 
    
    if step % 30 == 0:
        print(step, "\ncost : ", cost_val, "\nPrediction :", hy_val)

0 
cost :  100165.63 
Prediction : [[-144.77475]
 [-174.71465]
 [-172.07088]
 [-184.19113]
 [-136.01857]
 [ -95.30952]
 [-132.82216]
 [ -91.40794]
 [-159.47365]
 [-140.61266]
 [-131.47235]
 [-128.6832 ]
 [-181.10866]
 [-155.18674]
 [-133.17476]
 [-174.15614]
 [-151.91347]
 [-157.25348]
 [-173.06223]
 [-154.1651 ]
 [-157.04167]
 [-160.69191]
 [-150.58125]
 [-153.681  ]
 [-182.50388]]
30 
cost :  18.989632 
Prediction : [[152.78941 ]
 [182.91924 ]
 [180.31891 ]
 [199.56693 ]
 [136.75027 ]
 [105.757866]
 [154.40569 ]
 [121.48584 ]
 [174.73227 ]
 [168.89552 ]
 [145.27534 ]
 [144.18297 ]
 [182.98027 ]
 [147.50735 ]
 [155.3694  ]
 [188.73894 ]
 [136.38525 ]
 [187.43716 ]
 [174.04951 ]
 [156.41449 ]
 [179.78456 ]
 [174.79662 ]
 [170.56297 ]
 [146.38477 ]
 [188.154   ]]
60 
cost :  18.734747 
Prediction : [[152.8043  ]
 [182.92621 ]
 [180.3331  ]
 [199.56178 ]
 [136.76985 ]
 [105.73919 ]
 [154.37425 ]
 [121.424286]
 [174.71106 ]
 [168.82935 ]
 [145.26295 ]
 [144.15802 ]
 [183.0159  ]
 [147.565

930 
cost :  13.285889 
Prediction : [[153.12431]
 [183.13008]
 [180.66876]
 [199.42334]
 [137.29576]
 [105.32682]
 [153.57062]
 [119.85554]
 [174.24316]
 [167.26474]
 [144.95258]
 [143.57854]
 [183.87708]
 [148.99158]
 [154.44368]
 [188.47005]
 [138.37692]
 [186.1482 ]
 [175.01749]
 [157.20572]
 [178.96503]
 [174.49365]
 [169.94754]
 [147.9651 ]
 [188.65079]]
960 
cost :  13.1509695 
Prediction : [[153.13217]
 [183.13718]
 [180.67815]
 [199.41904]
 [137.31256]
 [105.31645]
 [153.54639]
 [119.80828]
 [174.23145]
 [167.22148]
 [144.94348]
 [143.56293]
 [183.90169]
 [149.03271]
 [154.41737]
 [188.4636 ]
 [138.43304]
 [186.11047]
 [175.04364]
 [157.2267 ]
 [178.94144]
 [174.4862 ]
 [169.92943]
 [148.00757]
 [188.6654 ]]
990 
cost :  13.018798 
Prediction : [[153.13983]
 [183.14424]
 [180.68741]
 [199.41473]
 [137.32927]
 [105.30628]
 [153.52234]
 [119.76142]
 [174.21997]
 [167.17885]
 [144.93445]
 [143.54756]
 [183.926  ]
 [149.07338]
 [154.39131]
 [188.45724]
 [138.48859]
 [186.07306]
 [

1770 
cost :  10.378244 
Prediction : [[153.28534]
 [183.32494]
 [180.88907]
 [199.31271]
 [137.7335 ]
 [105.10763]
 [152.96504]
 [118.67599]
 [173.99661]
 [166.26067]
 [144.7297 ]
 [143.22456]
 [184.46494]
 [149.98277]
 [153.79662]
 [188.33308]
 [139.74748]
 [185.19984]
 [175.63353]
 [157.6928 ]
 [178.3803 ]
 [174.33339]
 [169.49   ]
 [148.96266]
 [189.01854]]
1800 
cost :  10.301653 
Prediction : [[153.28917 ]
 [183.33171 ]
 [180.89548 ]
 [199.30911 ]
 [137.74791 ]
 [105.10215 ]
 [152.94598 ]
 [118.638916]
 [173.99048 ]
 [166.23177 ]
 [144.72285 ]
 [143.21469 ]
 [184.48248 ]
 [150.01266 ]
 [153.77663 ]
 [188.32964 ]
 [139.78947 ]
 [185.1698  ]
 [175.6516  ]
 [157.7068  ]
 [178.36201 ]
 [174.32924 ]
 [169.47542 ]
 [148.99179 ]
 [189.03021 ]]
1830 
cost :  10.226551 
Prediction : [[153.29288 ]
 [183.33847 ]
 [180.90184 ]
 [199.30557 ]
 [137.76225 ]
 [105.09681 ]
 [152.92711 ]
 [118.602165]
 [173.98453 ]
 [166.20332 ]
 [144.7161  ]
 [143.20502 ]
 [184.49983 ]
 [150.04224 ]
 [153.75684 ]

2430 
cost :  8.99489 
Prediction : [[153.34662 ]
 [183.46947 ]
 [181.01213 ]
 [199.23936 ]
 [138.0321  ]
 [105.015274]
 [152.58116 ]
 [117.92955 ]
 [173.8943  ]
 [165.71326 ]
 [144.59401 ]
 [143.04225 ]
 [184.8065  ]
 [150.56871 ]
 [153.39854 ]
 [188.27524 ]
 [140.57962 ]
 [184.59186 ]
 [175.98125 ]
 [157.95839 ]
 [178.01442 ]
 [174.26149 ]
 [169.19435 ]
 [149.52104 ]
 [189.25545 ]]
2460 
cost :  8.9449 
Prediction : [[153.3484  ]
 [183.4758  ]
 [181.01689 ]
 [199.23628 ]
 [138.04478 ]
 [105.01232 ]
 [152.56534 ]
 [117.898834]
 [173.89107 ]
 [165.69234 ]
 [144.58853 ]
 [143.0355  ]
 [184.82    ]
 [150.59209 ]
 [153.38237 ]
 [188.27338 ]
 [140.61322 ]
 [184.56671 ]
 [175.9948  ]
 [157.96854 ]
 [177.99944 ]
 [174.25906 ]
 [169.18207 ]
 [149.54271 ]
 [189.26527 ]]
2490 
cost :  8.895843 
Prediction : [[153.35011 ]
 [183.48212 ]
 [181.0216  ]
 [199.23325 ]
 [138.05739 ]
 [105.00945 ]
 [152.54967 ]
 [117.868385]
 [173.88794 ]
 [165.6717  ]
 [144.58311 ]
 [143.02888 ]
 [184.83336 ]
 [150.61

3390 
cost :  7.780419 
Prediction : [[153.37273]
 [183.66037]
 [181.13663]
 [199.15073]
 [138.40192]
 [104.95945]
 [152.13559]
 [117.06462]
 [173.83511]
 [165.1762 ]
 [144.44269]
 [142.87709]
 [185.16861]
 [151.202  ]
 [152.94984]
 [188.24011]
 [141.50491]
 [183.87874]
 [176.33762]
 [158.21896]
 [177.59506]
 [174.21078]
 [168.84503]
 [150.0875 ]
 [189.5346 ]]
3420 
cost :  7.752843 
Prediction : [[153.37271]
 [183.66592]
 [181.13972]
 [199.14827]
 [138.41232]
 [104.95876]
 [152.12349]
 [117.04115]
 [173.83447]
 [165.16321]
 [144.43869]
 [142.87335]
 [185.1779 ]
 [151.21843]
 [152.93788]
 [188.23967]
 [141.52937]
 [183.85925]
 [176.34653]
 [158.22527]
 [177.58376]
 [174.20995]
 [168.83543]
 [150.10155]
 [189.54225]]
3450 
cost :  7.725736 
Prediction : [[153.37265]
 [183.67146]
 [181.14278]
 [199.14583]
 [138.42268]
 [104.95814]
 [152.1115 ]
 [117.01789]
 [173.83391]
 [165.15044]
 [144.43472]
 [142.8697 ]
 [185.18706]
 [151.2347 ]
 [152.92604]
 [188.23927]
 [141.5536 ]
 [183.83992]
 [1

In [8]:
filename_queue = tf.train.string_input_producer(["data-01-test-score.csv"], shuffle=False, name="filename_queue")

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)

W0802 20:43:40.376669  8452 deprecation.py:323] From <ipython-input-7-506a957628b9>:25: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


0 Cost:  46320.633 
Prediction:
 [[-49.20727 ]
 [-68.40693 ]
 [-62.666767]
 [-68.6376  ]
 [-53.99783 ]
 [-41.1832  ]
 [-49.116035]
 [-33.048   ]
 [-66.39339 ]
 [-62.972553]]
10 Cost:  35.23351 
Prediction:
 [[157.13687]
 [179.6779 ]
 [181.73361]
 [197.54926]
 [135.21329]
 [ 98.34871]
 [150.13643]
 [114.66656]
 [165.4976 ]
 [151.85791]]
20 Cost:  29.360062 
Prediction:
 [[158.50885 ]
 [181.36526 ]
 [183.37575 ]
 [199.34581 ]
 [136.50298 ]
 [ 99.316605]
 [151.48256 ]
 [115.66523 ]
 [167.09343 ]
 [153.35747 ]]
30 Cost:  29.118216 
Prediction:
 [[158.49771]
 [181.38986]
 [183.37975]
 [199.35822]
 [136.52452]
 [ 99.34935]
 [151.49316]
 [115.67381]
 [167.13504]
 [153.4172 ]]
40 Cost:  28.902203 
Prediction:
 [[158.47731]
 [181.40314]
 [183.37271]
 [199.35857]
 [136.53743]
 [ 99.37564]
 [151.49472]
 [115.6757 ]
 [167.16602]
 [153.467  ]]
50 Cost:  28.688171 
Prediction:
 [[158.45697 ]
 [181.41634 ]
 [183.36566 ]
 [199.35887 ]
 [136.55026 ]
 [ 99.401794]
 [151.49623 ]
 [115.6775  ]
 [167.19682

550 Cost:  20.086802 
Prediction:
 [[157.54236]
 [182.0124 ]
 [183.05043]
 [199.36879]
 [137.13461]
 [100.57527]
 [151.5528 ]
 [115.73808]
 [168.57849]
 [155.7283 ]]
560 Cost:  19.950745 
Prediction:
 [[157.52597 ]
 [182.02316 ]
 [183.04482 ]
 [199.3689  ]
 [137.14523 ]
 [100.59625 ]
 [151.55359 ]
 [115.738754]
 [168.60318 ]
 [155.76765 ]]
570 Cost:  19.815866 
Prediction:
 [[157.50967 ]
 [182.03387 ]
 [183.03926 ]
 [199.36905 ]
 [137.15584 ]
 [100.61715 ]
 [151.5544  ]
 [115.739426]
 [168.6278  ]
 [155.80685 ]]
580 Cost:  19.682207 
Prediction:
 [[157.49344 ]
 [182.04454 ]
 [183.0337  ]
 [199.36916 ]
 [137.16638 ]
 [100.63797 ]
 [151.55516 ]
 [115.740074]
 [168.6523  ]
 [155.84586 ]]
590 Cost:  19.549702 
Prediction:
 [[157.47725]
 [182.05518]
 [183.02817]
 [199.36926]
 [137.17688]
 [100.65868]
 [151.55592]
 [115.7407 ]
 [168.6767 ]
 [155.88467]]
600 Cost:  19.418386 
Prediction:
 [[157.46117]
 [182.06577]
 [183.0227 ]
 [199.3694 ]
 [137.18738]
 [100.67931]
 [151.5567 ]
 [115.74132]
 

1050 Cost:  14.566327 
Prediction:
 [[156.80313]
 [182.50174]
 [182.79993]
 [199.37268]
 [137.62175]
 [101.52188]
 [151.58015]
 [115.75188]
 [169.6932 ]
 [157.49529]]
1060 Cost:  14.478953 
Prediction:
 [[156.78989 ]
 [182.51057 ]
 [182.79549 ]
 [199.3727  ]
 [137.63063 ]
 [101.538826]
 [151.58046 ]
 [115.75178 ]
 [169.71317 ]
 [157.52673 ]]
1070 Cost:  14.392382 
Prediction:
 [[156.77667 ]
 [182.51936 ]
 [182.79105 ]
 [199.37271 ]
 [137.63945 ]
 [101.55569 ]
 [151.58075 ]
 [115.751656]
 [169.73302 ]
 [157.55803 ]]
1080 Cost:  14.306509 
Prediction:
 [[156.76357]
 [182.52815]
 [182.78665]
 [199.37276]
 [137.64828]
 [101.57248]
 [151.58105]
 [115.75153]
 [169.75282]
 [157.58923]]
1090 Cost:  14.221477 
Prediction:
 [[156.7505 ]
 [182.53691]
 [182.78227]
 [199.37279]
 [137.65706]
 [101.58922]
 [151.58134]
 [115.7514 ]
 [169.77252]
 [157.62025]]
1100 Cost:  14.137143 
Prediction:
 [[156.73746 ]
 [182.5456  ]
 [182.7779  ]
 [199.3728  ]
 [137.6658  ]
 [101.60586 ]
 [151.5816  ]
 [115.75123

1530 Cost:  11.134489 
Prediction:
 [[156.2264  ]
 [182.88971 ]
 [182.60802 ]
 [199.37234 ]
 [138.01399 ]
 [102.25889 ]
 [151.58641 ]
 [115.733765]
 [170.5613  ]
 [158.85689 ]]
1540 Cost:  11.077375 
Prediction:
 [[156.21558]
 [182.89705]
 [182.60446]
 [199.37231]
 [138.02148]
 [102.2727 ]
 [151.58638]
 [115.73313]
 [170.57756]
 [158.88225]]
1550 Cost:  11.020751 
Prediction:
 [[156.20479]
 [182.90436]
 [182.60092]
 [199.37227]
 [138.02892]
 [102.28645]
 [151.58633]
 [115.73248]
 [170.59375]
 [158.90752]]
1560 Cost:  10.964616 
Prediction:
 [[156.19406 ]
 [182.91165 ]
 [182.59738 ]
 [199.37222 ]
 [138.03635 ]
 [102.30014 ]
 [151.58627 ]
 [115.731834]
 [170.60988 ]
 [158.93265 ]]
1570 Cost:  10.908949 
Prediction:
 [[156.18336]
 [182.9189 ]
 [182.59386]
 [199.37218]
 [138.04376]
 [102.31378]
 [151.58623]
 [115.73118]
 [170.62595]
 [158.95769]]
1580 Cost:  10.8538265 
Prediction:
 [[156.17274]
 [182.92613]
 [182.59036]
 [199.37213]
 [138.05115]
 [102.32737]
 [151.58618]
 [115.73051]
 [17