In [1]:
import tensorflow as tf

In [12]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder(tf.float32, [None, 3])
W = tf.Variable(tf.random_normal([3, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)

is_correct = tf.equal(prediction, tf.argmax(Y, 1))

accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y:y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.978216 [[-0.972089    0.04532895  1.7075138 ]
 [-2.0970283  -0.6587871   1.3082337 ]
 [ 0.36834538  1.2370799  -0.36096054]]
1 5.7766886 [[-0.9470949   0.03877592  1.6890727 ]
 [-1.9345406  -0.6377241   1.1246831 ]
 [ 0.5308365   1.2296411  -0.5160129 ]]
2 4.8821955 [[-0.92211044  0.00809865  1.6947654 ]
 [-1.7720741  -0.7471566   1.0716491 ]
 [ 0.69331074  1.0975964  -0.54644245]]
3 4.0372667 [[-0.897161   -0.01159386  1.6895086 ]
 [-1.6096889  -0.7975864   0.9596936 ]
 [ 0.85568154  1.0210259  -0.6322427 ]]
4 3.2151885 [[-0.87235135 -0.03575471  1.6888597 ]
 [-1.4476489  -0.8728436   0.87291086]
 [ 1.0175508   0.9211175  -0.69420356]]
5 2.4036849 [[-0.848335   -0.05689437  1.6859831 ]
 [-1.2878295  -0.9337709   0.77401876]
 [ 1.175998    0.8362377  -0.767771  ]]
6 1.650253 [[-0.82907057 -0.0755178   1.685342  ]
 [-1.1455699  -0.9891554   0.68714374]
 [ 1.3110702   0.7634088  -0.8300143 ]]
7 1.2301364 [[-0.8306042  -0.07910714  1.690465  ]
 [-1.1041621  -0.9771008   0.6336813 ]
 [

126 0.6581664 [[-1.4748665  -0.57277125  2.828391  ]
 [-0.4754266  -0.6323491  -0.33980516]
 [ 0.9171176   0.5942635  -0.26691592]]
127 0.6564666 [[-1.4792341  -0.5750474   2.8350348 ]
 [-0.4731875  -0.630341   -0.34405234]
 [ 0.9164891   0.59324765 -0.2652716 ]]
128 0.654793 [[-1.4835881  -0.5772983   2.8416398 ]
 [-0.47098032 -0.62836456 -0.34823596]
 [ 0.9158921   0.5922582  -0.26368517]]
129 0.65314513 [[-1.4879285  -0.57952416  2.848206  ]
 [-0.46880475 -0.6264195  -0.35235658]
 [ 0.9153263   0.59129477 -0.2621559 ]]
130 0.6515223 [[-1.4922556  -0.58172524  2.8547342 ]
 [-0.46666053 -0.6245055  -0.35641477]
 [ 0.9147911   0.59035707 -0.260683  ]]
131 0.64992404 [[-1.4965693  -0.5839018   2.8612244 ]
 [-0.46454725 -0.62262243 -0.36041114]
 [ 0.9142864   0.5894446  -0.25926575]]
132 0.64834976 [[-1.5008699  -0.586054    2.8676772 ]
 [-0.46246478 -0.6207697  -0.36434633]
 [ 0.91381145  0.5885571  -0.25790343]]
133 0.6467991 [[-1.5051574  -0.58818215  2.8740928 ]
 [-0.4604126  -0.6189

Prediction: [2 2 2]
accuracy: 1.0


In [15]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder(tf.float32, [None, 3])
W = tf.Variable(tf.random_normal([3, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.3).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)

is_correct = tf.equal(prediction, tf.argmax(Y, 1))

accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y:y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.3476515 [[ 0.36630118 -0.9200222   1.0212661 ]
 [ 2.6146176  -1.5656687   0.2751007 ]
 [ 0.90715325 -3.1062493   0.9897404 ]]
1 16.57563 [[-0.5576496 -0.4325224  1.4577171]
 [-0.8531382  0.7093309  1.4678568]
 [-2.5012603 -0.6687498  1.960654 ]]
2 19.965542 [[-0.23264971  0.05490518  0.6452896 ]
 [ 1.2593615   2.9841838  -2.9194956 ]
 [-0.38876033  1.7686753  -2.5892708 ]]
3 16.164858 [[ 0.09227276 -0.7575172   1.1327896 ]
 [ 3.3717048  -0.42815924 -1.6194957 ]
 [ 1.7236605  -1.4812453  -1.4517709 ]]
4 19.237724 [[-0.8827153  -0.27001992  1.6202803 ]
 [-0.20327091  1.8468354  -0.3195144 ]
 [-1.8513274   0.9562521  -0.31428027]]
5 10.515242 [[-0.5577249  -1.0622542   2.0875242 ]
 [ 1.9092097  -1.5243728   0.9392129 ]
 [ 0.261163   -2.272065    0.80154645]]
6 13.340492 [[-0.25685546 -0.57475436  1.2991548 ]
 [ 3.8717203   0.7506268  -3.2982974 ]
 [ 2.249568    0.16543484 -3.6243587 ]]
7 19.702951 [[-1.2317629  -0.08734694  1.7866547 ]
 [ 0.296906    3.0254412  -1.9982976 ]
 [-1.32533

122 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
123 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
124 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
125 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
126 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
127 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
128 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
129 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
130 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
131 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
132 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
133 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
134 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
135 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
136 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
137 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
138 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
139 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
140 nan [[nan nan nan]
 [nan

In [14]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder(tf.float32, [None, 3])
W = tf.Variable(tf.random_normal([3, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)

is_correct = tf.equal(prediction, tf.argmax(Y, 1))

accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y:y_data})
        print(step, cost_val, W_val)
        
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
1 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
2 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
3 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
4 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
5 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
6 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
7 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.873

 [ 0.8734207  -2.346       1.0411934 ]]
115 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
116 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
117 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
118 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
119 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
120 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
121 7.383151 [[ 0.666737    0.39085528 -0.63227695]
 [ 0.49285868  0.70927596  0.89711183]
 [ 0.8734207  -2.346       1.0411934 ]]
122 7.383151 [[ 0.666737    0.39085528 -0.6