In [10]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler 

In [11]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler().fit_transform(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.6980039 
Prediction:
 [[ 0.6086906 ]
 [ 1.2308582 ]
 [ 0.30755174]
 [-0.6822518 ]
 [-0.17232478]
 [-0.29260933]
 [-1.2339249 ]
 [-0.9515103 ]]
1 Cost:  0.69798124 
Prediction:
 [[ 0.6087154 ]
 [ 1.2308828 ]
 [ 0.30757296]
 [-0.68223405]
 [-0.17230487]
 [-0.29258978]
 [-1.2339096 ]
 [-0.95149535]]
2 Cost:  0.69795847 
Prediction:
 [[ 0.6087402 ]
 [ 1.2309068 ]
 [ 0.30759418]
 [-0.68221617]
 [-0.17228472]
 [-0.29257023]
 [-1.2338945 ]
 [-0.95148045]]
3 Cost:  0.6979358 
Prediction:
 [[ 0.60876524]
 [ 1.2309314 ]
 [ 0.30761564]
 [-0.68219817]
 [-0.1722647 ]
 [-0.29255068]
 [-1.2338793 ]
 [-0.9514656 ]]
4 Cost:  0.6979131 
Prediction:
 [[ 0.60879004]
 [ 1.2309557 ]
 [ 0.30763686]
 [-0.6821803 ]
 [-0.17224467]
 [-0.29253113]
 [-1.2338641 ]
 [-0.9514507 ]]
5 Cost:  0.6978904 
Prediction:
 [[ 0.60881484]
 [ 1.23098   ]
 [ 0.3076583 ]
 [-0.6821624 ]
 [-0.17222464]
 [-0.29251158]
 [-1.233849  ]
 [-0.9514358 ]]
6 Cost:  0.6978677 
Prediction:
 [[ 0.60883987]
 [ 1.2310044 ]
 [ 0.307679

In [12]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler().fit_transform(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.15336603 
Prediction:
 [[ 0.45824063]
 [ 0.5069937 ]
 [ 0.27910715]
 [-0.03135645]
 [ 0.19912004]
 [ 0.11211634]
 [-0.1702246 ]
 [-0.36733347]]
1 Cost:  0.15335524 
Prediction:
 [[ 0.45825952]
 [ 0.50701195]
 [ 0.27912253]
 [-0.03134432]
 [ 0.19913429]
 [ 0.11213011]
 [-0.17021513]
 [-0.36732414]]
2 Cost:  0.15334448 
Prediction:
 [[ 0.45827842]
 [ 0.5070302 ]
 [ 0.2791379 ]
 [-0.03133219]
 [ 0.19914848]
 [ 0.11214381]
 [-0.17020562]
 [-0.36731482]]
3 Cost:  0.1533337 
Prediction:
 [[ 0.4582973 ]
 [ 0.5070485 ]
 [ 0.27915335]
 [-0.03132004]
 [ 0.19916266]
 [ 0.11215758]
 [-0.17019615]
 [-0.36730552]]
4 Cost:  0.1533229 
Prediction:
 [[ 0.4583162 ]
 [ 0.5070668 ]
 [ 0.27916873]
 [-0.03130794]
 [ 0.19917685]
 [ 0.11217135]
 [-0.17018664]
 [-0.3672962 ]]
5 Cost:  0.15331213 
Prediction:
 [[ 0.4583351 ]
 [ 0.5070851 ]
 [ 0.27918416]
 [-0.03129578]
 [ 0.19919103]
 [ 0.11218506]
 [-0.17017716]
 [-0.36728686]]
6 Cost:  0.15330136 
Prediction:
 [[ 0.458354  ]
 [ 0.5071033 ]
 [ 0.279

 [-0.36641192]]
100 Cost:  0.15229079 
Prediction:
 [[ 0.46012947]
 [ 0.508821  ]
 [ 0.28064594]
 [-0.03014338]
 [ 0.20054004]
 [ 0.11349025]
 [-0.16927603]
 [-0.36640263]]
